---

- name: Identify user
  debug:
    msg: "Ansible_user is: {{ ansible_user }}"

- name: Set ssh key for {{ ansible_user }} user
  become: false
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ pibasic_piuser_sshkey }}"
  when:
    - pibasic_piuser_sshkey is defined
    - pibasic_piuser_sshkey | length > 0

- name: Change the {{ ansible_user }} user password
  user:
    name: "{{ ansible_user }}"
    password: "{{ pibasic_piuser_password |
      password_hash('sha512', pibasic_pwhash_salt) }}"
  when:
    - pibasic_piuser_password is defined
    - pibasic_piuser_password | length > 0

- name: Set hostname to {{ pibasic_hostname }}
  hostname:
    name: "{{ pibasic_hostname }}"

- name: Update hosts file with hostname
  replace:
    path: /etc/hosts
    regexp: 'raspberrypi'
    replace: "{{ pibasic_hostname }}"

- name: Set timezone to {{ pibasic_timezone }}
  timezone:
    name: "{{ pibasic_timezone }}"

- name: Update keyboard layout
  lineinfile:
    path: /etc/default/keyboard
    regexp: 'XKBLAYOUT=.*'
    line: 'XKBLAYOUT="us"'

- name: Backup vanilla config.txt
  copy:
    remote_src: yes
    src: /boot/config.txt
    dest: /boot/config.vanilla.txt
    force: no

- name: Setup pi config.txt
  lineinfile:
    path: /boot/config.txt
    regex: "{{ item.regex }}"
    line: "{{ item.newline }}"
  loop:
    - regex: '#?gpu_mem=.*'
      newline: "gpu_mem={{ pibasic_gpumem }}"
    - regex: '#?dtparam=.*audio=.*'
      newline: "dtparam=audio={{ 'on' if pibasic_audio | bool else 'off' }}"
    - regex: '#?disable_overscan=.*'
      newline: "disable_overscan=1"
  loop_control:
    label: "{{ item.newline }}"
  register: piconfigupdate
  notify: Reboot system

- name: Put /var/log on ramdisk
  mount:
    state: present
    src: tmpfs
    path: /var/log
    fstype: tmpfs
    opts: defaults,noatime,nosuid,mode=0755,size=200m
  notify: Reboot system
  when: pibasic_ramdisk_log | bool

- import_tasks: nasmount.yml
  when: pibasic_nas_mount | bool

- name: Install a few packages
  apt:
    name:
      - tmux
    update_cache: true

- name: Add tmux conf
  copy: 
    src: tmux.conf
    dest: "{{ item.home }}/.tmux.conf"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    mode: "0644"
  loop:
    - { user: root, home: /root }
    - { user: pi, home: /home/pi }

- name: Perform apt update
  apt:
    upgrade: safe
    update_cache: true
  tags:
    - aptupgrade
