---

- name: Download pihole installer
  get_url:
    url: "{{ pihole_url }}"
    dest: /root/install-pihole.sh
    mode: 0700

- name: Create pihole configuration directory
  file:
    name: "{{ pihole_conf_dir }}"
    state: directory
    owner: '999' # uid=pihole, which doesn't exist yet
    group: '995' # gid=pihole, which doesn't exist yet
    mode: 0775

- name: Check for pihole configuration backup
  stat:
    path: "{{ pihole_conf_dir }}/setupVars.conf.update.bak"
  register: config_stat

- name: Create pihole configuration
  template:
    src: setupVars.conf.j2
    dest: "{{ pihole_conf_dir }}/setupVars.conf"
    owner: root
    group: root
    mode: 0644
  when: config_stat.stat.exists == false

- name: Install pihole
  command:
    cmd: /root/install-pihole.sh --unattended
    creates: /etc/pihole/install.log

- name: Tweak pihole config
  lineinfile:
    path: /etc/pihole/pihole-FTL.conf
    line: "{{ item }}"
  notify: Restart pihole
  loop:
    - "DBINTERVAL=60" #mins. only write db this often (default is 1min)
    - "AAAA_QUERY_ANALYSIS=yes" #for ipv6 queries to work?
