---

#target
pisdsetup_dest: "/boot"

#create the userconf file
pisdsetup_userconf_enable: true
pisdsetup_piuser: pi
pisdsetup_piuser_password: raspberry #the original default, should be overridden

#wifi settings
pisdsetup_wifi_enable: true
pisdsetup_wifi_country: "AU"

# Blank means don't configure
pisdsetup_wifi_ssid: "{{ vault_wifi_network_ssid | default('') }}"
pisdsetup_wifi_psk: "{{ vault_wifi_network_psk | default('') }}"

# Also produce the preboot ssh enable flag file
pisdsetup_ssh_enable: true
