---

- name: Setup pi config.txt for RTC
  lineinfile:
    path: /boot/config.txt
    regex: "{{ item.regex }}"
    line: "{{ item.newline }}"
  loop:
    - { regex: '#?dtparam=.*i2c_arm=.*', newline: "dtparam=i2c_arm=on" }
    - { regex: '#?dtoverlay=.*i2c-rtc.*', newline: "dtoverlay=i2c-rtc,ds3231" }
  loop_control:
    label: "{{ item.newline }}"
  register: piconfigupdatertc
  when: pirtc_enable|bool
  notify: Reboot system

- name: Install some packages for RTC support
  apt:
    name:
      - i2c-tools
    update_cache: true
  when: pirtc_enable|bool

- name: Setup RTC kernel module
  modprobe:
    name: rtc-ds3232
  when: pirtc_enable|bool

- name: I2C scan for RTC
  command:
    cmd: i2cdetect -y 1 0x68 0x68
  register: i2cdetect
  changed_when: false
  when: pirtc_enable|bool

- debug:
    var: i2cdetect

- debug:
    msg: "i think we have rtc"
  when:
    - i2cdetect.stdout_lines[7] is defined
    - '"68" in i2cdetect.stdout_lines[7]'

#i2cdetect -y 1 0x68 0x68

#RTC clock change BUT ONLY IF THE HARDWARE IS PRESENT
#    - name: Install some packages for RTC support
#      apt:
#        name: fake-hwclock
#        state: absent
#        autoclean: yes
#        autoremove: yes
#      when: pirtc_enable|bool
