---

- name: Generate the userconf file
  copy:
    content: "{{ piwifi_piuser }}:{{ piwifi_piuser_password | password_hash('sha512') }}"
    dest: "{{ piwifi_dest }}/userconf"
  when: piwifi_userconf_enable | bool
#https://www.raspberrypi.com/news/raspberry-pi-bullseye-update-april-2022/
#echo 'mypassword' | openssl passwd -6 -stdin

- name: Install wpa_supplicant configuraiton
  template:
    src: wpa_supplicant.conf.j2
    dest: "{{ piwifi_dest }}/wpa_supplicant.conf"
  when: 
    - piwifi_enabled | bool
    - piwifi_ssid | length > 0

- name: Create the preboot ssh enable file
  copy:
    content: ""
    dest: "{{ piwifi_dest }}/ssh"
  when: piwifi_ssh_enable | bool
  