---

pibasic_piuser_password: {{ vault_piuser_password | default('raspberry') }}
pibasic_piuser_sshkey: {{ vault_piuser_sshkey | default('') }}

vault_piuser_password: "raspberry"
vault_piuser_sshkey: "ssh-rsa xxxx user@box"

#vault_pihole_admin_password: "password"
vault_pihole_admin_password: "113459eb7bb31bddee85ade5230d6ad5d8b2fb52879e00a84ff6ae1067a210d3"
# echo -n password | sha256sum | awk '{printf "%s",$1 }' | sha256sum
# 113459eb7bb31bddee85ade5230d6ad5d8b2fb52879e00a84ff6ae1067a210d3  -
