---

# System defaults:
pibasic_hostname: "pi"
pibasic_timezone: "UTC"

# When set to empty string, it means do not change
pibasic_piuser_password: "{{ vault_piuser_password | default('') }}"
pibasic_piuser_sshkey: "{{ vault_piuser_sshkey | default('') }}"

# By fixing the salt to a value it makes setting the password idempotent
pibasic_pwhash_salt: "HZYXyiX9G5TPH"
