---
# This play is to generate the supplicant config for an SD card writing process.

# Used like this (for example, with local inventory):
# ansible-playbook -i '127.0.0.1,' basicwificonfig.yml -e piwifi_dest=/tmp/

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - piwifi_dest: /tmp
    - ansible_python_interpreter: /usr/bin/python3
  tasks:
    - import_role:
        name: pi-wifi
