---
# This play is to generate the supplicant config for an SD card writing process.

# Used like this (for example, with local inventory):
# ansible-playbook basicwificonfig.yml -e piwifi_dest=/tmp/

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    piwifi_dest: /tmp
  tasks:
    - import_role:
        name: pi-wifi
      vars:
        piwifi_userconf_enable: true
        piwifi_enabled: true
        piwifi_ssh_enable: true
        piwifi_piuser_password: "{{ vault_piuser_password }}"
