---
# This play is to generate the supplicant config for an SD card writing process.
# It also enables ssh and sets the user account up.

# Used like this (for example, with local inventory):
# ansible-playbook basic-sdsetup.yml -e pisdsetup_dest=/tmp/

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    pisdsetup_dest: /tmp
  tasks:
    - import_role:
        name: pi-wifi
      vars:
        pisdsetup_userconf_enable: true
        pisdsetup_wifi_enable: true
        pisdsetup_ssh_enable: true
        pisdsetup_piuser_password: "{{ vault_piuser_password }}"
