---
# Pihole on a real pi

# Pre-reqs:
# * Out of box, raspios (raspbian) pi WITH SSH enabled

# Initial ansible connection test:
# ansible pi -m setup -e "ansible_password=raspberry ansible_user=pi" -e \
# "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o AddressFamily=inet'"

# Provision a pihole:
# ansible-playbook setup-pihole.yml --limit=<hostpattern>

- hosts: pi
  remote_user: pi
  become: yes
  vars:
    ansible_password: raspberry #this is the initial password only, and gets changed

  tasks:
    - import_role:
        name: pi-basic

    - import_role:
        name: pi-rtc

    - import_role:
        name: pi-pihole
