---
# Pihole on a real pi

# Pre-reqs:
# * Out of box, raspios (raspbian) pi WITH SSH enabled and user pi created with vaulted password

# Initial ansible connection test: (this assumes raspberrypi resolves in dns)
# ansible pi -m setup -e "ansible_password='{{vault_piuser_password}}' ansible_user=pi" --limit=raspberrypi
# (this is using group pi, so the ssh ansible_ssh_common_args are set)

# Provision a pihole:
# ansible-playbook setup-pihole.yml --limit=<hostpattern>

- hosts: pi
  remote_user: pi
  become: yes
  vars:
    ansible_password: "{{ vault_piuser_password }}" #was raspberry bullseye and on it's no longer defaulted

  tasks:
    - import_role:
        name: pi-basic
      vars:
        pibasic_ramdisk_log: true

    - import_role:
        name: pi-rtc

    - import_role:
        name: pi-pihole
