---
# Setup an everyday pi

# Pre-reqs:
# * Out of box, raspios (raspbian) pi WITH SSH enabled

# Initial ansible connection test:
# ansible pi -m setup -e "ansible_password=raspberry ansible_user=pi" --limit=einkpi -e \
# "ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o AddressFamily=inet'"

# Provision:
# initially (out of box hostname=raspberrypi, so override hostname you want to set)
#   ansible-playbook setup-pi.yml --limit=raspberrypi -e pibasic_hostname=einkpi
# Then afterwards hostvars file overides hostname
# ansible-playbook setup-pi.yml --limit=einkpi

- hosts: pi
  remote_user: pi
  become: yes
  vars:
    ansible_password: raspberry #this is the initial password only, and gets changed

  tasks:
    - import_role:
        name: pi-basic
      vars:
        pibasic_nas_mount: true

    - import_role:
        name: pi-eink
